### ISSUE TITLE
Riviera-PRO common compilation

### ISSUE THREAD

**Issue by dawidzim** [chipsalliance/Cores-SweRVolf#12]
Is there any option to automatized merge Edalize version with Riviera-PRO common compilation mode to FuseSoC?
Now I must install FuseSoC, download new version of Edalize and copy `rivierapro.py` to main folder of Edalize

**Comment by olofk** [comment]
If I understand correctly, the problem will be resolved once I have released a new version of Edalize. I should probably do that very soon anyway for many reasons.

In the meantime I think you can install the development version of Edalize with `pip3 install git+https://github.com/olofk/edalize`

**Comment by dawidzim** [comment]
Thanks, thats works for me!
