### ISSUE TITLE
Running pre-compiled zephyr examples failed

### ISSUE THREAD

**Issue by cst-kirank** [chipsalliance/Cores-SweRVolf#20]
When I tried to run precompiled Zephyr examples it failed giving the following reason,
": $readmem file not found"
Aborting...
ERROR: Failed to run ::swervolf:0.7 : './Vswervolf_core_tb' exited with an error code

It would be great to know what caused this unexpected error.

Thanks,
Kiran Khunte

**Comment by olofk** [comment]
It looks like the path to the program you want to load is incorrect. What does you command line look like? I expect it would be something like `fusesoc run --target=sim swervolf --ram_init_file fusesoc_libraries/swervolf/sw/zephyr_hello.vh`, if you used the default installation directories

**Comment by cst-kirank** [comment]
Thanks!
The problem was with the library path.
