### ISSUE TITLE
fusesoc run --target=arty_a7 swervolf

### ISSUE THREAD

**Issue by nimra471** [chipsalliance/Cores-SweRVolf#57]
================================================================================
INFO: Generating ::swervolf-swerv_el2_arty_a7_config:0.7.4
Can't locate Bit/Vector.pm in @INC (you may need to install the Bit::Vector module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at configs/swerv.config line 6.
BEGIN failed--compilation aborted at configs/swerv.config line 6.
ERROR: Setup failed : "python3 /home/nkhan/.cache/fusesoc/chipsalliance.org_cores_SweRV_EL2_1.3/configs/swerv_config_gen.py /home/nkhan/.cache/fusesoc/generated/swervolf-swerv_el2_arty_a7_config_0.7.4/swerv_el2_arty_a7_config_input.yml" exited with an error code. See stderr for details.

**Comment by olofk** [comment]
You need to install the perl package that contains Bit::Vector. The name of the package depends on which Linux distribution you're using, but on Gentoo it's called `dev-perl/Bit-Vector` and it looks like it's called `libbit-vector-perl` in Debian/Ubuntu
