### ISSUE TITLE
SweRV EL2 with  External Sram memory issue

### ISSUE THREAD

**Issue by nimra471** [chipsalliance/Cores-SweRVolf#60]
Hi,
I am going to do ASIC of SweRV EL2 for that I am using SRAM as a external memory with a memory  controller (axi2mem sram adapter) but I am facing a issue during fetching instruction, core is fetching the instruction only at the starting  `address` of the instruction which is 0000000 and remain same at all the cycle.
![image](https://user-images.githubusercontent.com/81620928/209725446-9da25f68-3d2a-4136-a3a2-8e8501bb8505.png)
The above pictures shows the simulation of SweRV EL2 in which at the dout0 sram signal , only 2 3 instruction is reading 
![image](https://user-images.githubusercontent.com/81620928/209726258-e84ffd21-2867-480e-8010-189bf674074d.png)
In he second picture . the ifu_axi_aradder is not incremented and not getting ifu_axi_rvalid. Where as it is working fine with blockRAM on fpga using xilinx ip block memory generator
Here is https://github.com/merledu/Rev-Soc-ASIC.git
instantiate SRAM in the design/Rev-top

**Comment by olofk** [comment]
It doesn't look like you are using SweRVolf but some custom SoC that uses the EL2 CPU, so I'm afraid I can't help you with this.
